# Generated by Django 3.2.7 on 2021-09-28 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shred', '0005_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
