# Generated by Django 3.2.7 on 2021-09-30 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shred', '0006_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beach',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
